### ISSUE TITLE
Страницы перепутаны.

### ISSUE THREAD

**Issue by Alessa19** [Romancha/litnet-book-saver#1]
Страницы перепутаны. Некоторые страницы повторяются, другие отсутствуют.

**Comment by Romancha** [comment]
@Alessa19 Пример можете прислать?

**Comment by Alessa19** [comment]
https://litnet.com/ru/reader/quottri-zvezdyquot-dlya-styuardessy-b322045

**Comment by Romancha** [comment]
@Alessa19 Исправлено в версии 1.2

**Comment by Alessa19** [comment]
@Romancha Теперь работает идеально, спасибо.
